apiVersion: apps/v1
kind: Deployment
metadata:
    name: spring-boot
    annotations:
        git.tag: 1.0.0
    labels:
        app.kubernetes.io/name: spring-boot
        app.kubernetes.io/version: 1.0.0
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/name: spring-boot
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    template:
        metadata:
            labels:
                app.kubernetes.io/name: spring-boot
                app.kubernetes.io/version: 1.0.0
        spec:
            containers:
                - name: spring-boot
                  image: nonnemacher/spring-boot:1.0.0
                  imagePullPolicy: Always
                  ports:
                      - name: http
                        containerPort: 8080
                        protocol: TCP
                  livenessProbe:
                      failureThreshold: 3
                      httpGet:
                          path: /info
                          port: http
                          scheme: HTTP
                      initialDelaySeconds: 5
                      periodSeconds: 20
                      successThreshold: 1
                      timeoutSeconds: 3
                  readinessProbe:
                      failureThreshold: 3
                      httpGet:
                          path: /info
                          port: http
                          scheme: HTTP
                      initialDelaySeconds: 5
                      periodSeconds: 10
                      successThreshold: 1
                      timeoutSeconds: 3
                  resources:
                      limits:
                          memory: 128Mi
                          cpu: 500m
