apiVersion: v1
kind: Service
metadata:
    name: spring-boot
    labels:
        app.kubernetes.io/name: spring-boot
        app.kubernetes.io/version: 1.0.0
spec:
    type: LoadBalancer
    ports:
        - port: 8080
          targetPort: http
          protocol: TCP
          name: http
    selector:
        app.kubernetes.io/name: spring-boot
